[package]
name = "rust-proxy"
version = "0.1.0"
authors = ["ctydw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
byteorder = "1.4.3"
bytes = "1.0.1"
env_logger = "0.9.0"
futures = { version = "0.3.15", features = ["thread-pool"]}
itertools = "0.10.0"
log = "0.4.14"
portpicker = "0.1.0"
rustls = { version = "0.19.1" }
serde_json = { version = "1.0" }
tokio = { version = "1.9.0", features = ["full"] }
tokio-util = { version = "0.6.7", features = ["full"] }
tokio-stream = { version = "0.1.7" }
tokio-rustls = "0.22.0"
webpki-roots = "0.21"