[package]
name = "rust-proc"
version = "0.1.0"
authors = ["ctydw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
tokio = { version = "1.5.0", features = ["full"] }